# Generated by Django 5.2.17 on 2026-08-26 20:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_auth_unmanaged_models'),
    ]

    operations = [
        migrations.RunSQL(
            sql='CREATE SCHEMA IF NOT EXISTS "gestion_documental"',
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
            name='AccionAuditoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': '"gestion_documental"."acciones_auditoria"',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='TipoRecursoAuditoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': '"gestion_documental"."tipos_recurso_auditoria"',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='EstadoDocumento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=32, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('es_final', models.BooleanField(default=False)),
                ('permite_edicion', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': '"gestion_documental"."estados_documento"',
                'ordering': ['orden', 'nombre'],
                'constraints': [models.CheckConstraint(condition=models.Q(('codigo__regex', '^[A-Z0-9_-]+$')), name='ck_estados_doc_codigo_formato'), models.CheckConstraint(condition=models.Q(('orden__gte', 0)), name='ck_estados_doc_orden_no_negativo')],
            },
        ),
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=32)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': '"gestion_documental"."organizaciones"',
                'ordering': ['nombre'],
                'constraints': [models.UniqueConstraint(fields=('codigo',), name='uq_organizaciones_codigo'), models.CheckConstraint(condition=models.Q(('codigo__regex', '^[A-Z0-9_-]+$')), name='ck_organizaciones_codigo_formato')],
            },
        ),
        migrations.CreateModel(
            name='ClasificacionDocumento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=32)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('nivel', models.PositiveSmallIntegerField(default=1)),
                ('requiere_autorizacion', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('organizacion', models.ForeignKey(db_column='organizacion_id', on_delete=django.db.models.deletion.CASCADE, related_name='clasificaciones_documento', to='documentos.organizacion')),
            ],
            options={
                'db_table': '"gestion_documental"."clasificaciones_documento"',
                'ordering': ['nivel', 'nombre'],
                'indexes': [models.Index(fields=['organizacion', 'activo'], name='ix_clasif_doc_org_activo')],
                'constraints': [models.UniqueConstraint(fields=('organizacion', 'codigo'), name='uq_clasif_doc_organizacion_codigo'), models.CheckConstraint(condition=models.Q(('codigo__regex', '^[A-Z0-9_-]+$')), name='ck_clasif_doc_codigo_formato'), models.CheckConstraint(condition=models.Q(('nivel__gte', 1)), name='ck_clasif_doc_nivel_positivo')],
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=32)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('organizacion', models.ForeignKey(db_column='organizacion_id', on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='documentos.organizacion')),
            ],
            options={
                'db_table': '"gestion_documental"."areas"',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['organizacion', 'activo'], name='ix_areas_org_activo')],
                'constraints': [models.UniqueConstraint(fields=('organizacion', 'codigo'), name='uq_areas_organizacion_codigo'), models.CheckConstraint(condition=models.Q(('codigo__regex', '^[A-Z0-9_-]+$')), name='ck_areas_codigo_formato')],
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=32)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('organizacion', models.ForeignKey(db_column='organizacion_id', on_delete=django.db.models.deletion.CASCADE, related_name='tipos_documento', to='documentos.organizacion')),
            ],
            options={
                'db_table': '"gestion_documental"."tipos_documento"',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['organizacion', 'activo'], name='ix_tipos_doc_org_activo')],
                'constraints': [models.UniqueConstraint(fields=('organizacion', 'codigo'), name='uq_tipos_doc_organizacion_codigo'), models.CheckConstraint(condition=models.Q(('codigo__regex', '^[A-Z0-9_-]+$')), name='ck_tipos_doc_codigo_formato')],
            },
                ),
            ],
        ),
    ]
