# Generated by Django 5.2.17 on 2026-08-26 22:17

import django.db.models.deletion
import documentos.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0003_permisodocumental_roldocumental_rolpermisodocumental_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=64)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('contenido', models.TextField(blank=True)),
                ('palabras_clave', models.TextField(blank=True)),
                ('alcance', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('archivado_en', models.DateTimeField(blank=True, null=True)),
                ('area', models.ForeignKey(blank=True, db_column='area_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='documentos.area')),
                ('clasificacion', models.ForeignKey(blank=True, db_column='clasificacion_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='documentos.clasificaciondocumento')),
                ('creado_por', models.ForeignKey(db_column='creado_por_id', on_delete=django.db.models.deletion.PROTECT, related_name='documentos_creados', to='documentos.usuariodocumental')),
                ('estado', models.ForeignKey(db_column='estado_id', on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='documentos.estadodocumento')),
                ('organizacion', models.ForeignKey(db_column='organizacion_id', on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='documentos.organizacion')),
                ('responsable', models.ForeignKey(db_column='responsable_id', on_delete=django.db.models.deletion.PROTECT, related_name='documentos_responsable', to='documentos.usuariodocumental')),
                ('tipo', models.ForeignKey(db_column='tipo_id', on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='documentos.tipodocumento')),
            ],
            options={
                'db_table': '"gestion_documental"."documentos"',
                'ordering': ['-actualizado_en', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='ArchivoDocumento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('archivo', models.FileField(upload_to=documentos.models.document_file_upload_to)),
                ('nombre_original', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=150)),
                ('tamano', models.BigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('subido_por', models.ForeignKey(db_column='subido_por_id', on_delete=django.db.models.deletion.PROTECT, related_name='archivos_subidos', to='documentos.usuariodocumental')),
                ('documento', models.ForeignKey(db_column='documento_id', on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='documentos.documento')),
            ],
            options={
                'db_table': '"gestion_documental"."archivos_documentos"',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='MetadatoDocumento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=100)),
                ('valor', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('documento', models.ForeignKey(db_column='documento_id', on_delete=django.db.models.deletion.CASCADE, related_name='metadatos', to='documentos.documento')),
            ],
            options={
                'db_table': '"gestion_documental"."documentos_metadatos"',
                'ordering': ['clave'],
            },
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['organizacion', 'estado'], name='ix_docs_org_estado'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['organizacion', 'actualizado_en'], name='ix_docs_org_actualizado'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['organizacion', 'area'], name='ix_docs_org_area'),
        ),
        migrations.AddConstraint(
            model_name='documento',
            constraint=models.UniqueConstraint(fields=('organizacion', 'codigo'), name='uq_documentos_organizacion_codigo'),
        ),
        migrations.AddConstraint(
            model_name='documento',
            constraint=models.CheckConstraint(condition=models.Q(('codigo__regex', '^[A-Z0-9_-]+$')), name='ck_documentos_codigo_formato'),
        ),
        migrations.AddIndex(
            model_name='archivodocumento',
            index=models.Index(fields=['documento', 'creado_en'], name='ix_archivos_doc_fecha'),
        ),
        migrations.AddIndex(
            model_name='archivodocumento',
            index=models.Index(fields=['sha256'], name='ix_archivos_sha256'),
        ),
        migrations.AddConstraint(
            model_name='metadatodocumento',
            constraint=models.UniqueConstraint(fields=('documento', 'clave'), name='uq_documentos_metadatos_documento_clave'),
        ),
    ]
