# Generated by Django 5.2.17 on 2026-08-26 23:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0005_areacatalogo_estadoversioncatalogo_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                "INSERT INTO gestion_documental.estados_version "
                "(id, codigo, nombre, es_final, permite_edicion) "
                "SELECT 6, 'PUBLICADO', 'Publicado', TRUE, FALSE "
                "WHERE NOT EXISTS ("
                "SELECT 1 FROM gestion_documental.estados_version WHERE codigo = 'PUBLICADO'"
                ");"
            ),
            reverse_sql=(
                "DELETE FROM gestion_documental.estados_version "
                "WHERE codigo = 'PUBLICADO';"
            ),
        ),
        migrations.RunSQL(
            sql=(
                "INSERT INTO gestion_documental.historial_estados_version "
                "(version_documento_id, estado_nuevo_id, cambiado_por_id, comentario, cambiado_en) "
                "SELECT v.id, v.estado_version_id, v.creada_por_id, "
                "'Version existente registrada en el historial', v.creada_en "
                "FROM gestion_documental.versiones_documento v "
                "WHERE NOT EXISTS ("
                "SELECT 1 FROM gestion_documental.historial_estados_version h "
                "WHERE h.version_documento_id = v.id"
                ");"
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name='EstadoRevisionCatalogo',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=32)),
                ('nombre', models.CharField(max_length=100)),
                ('es_final', models.BooleanField(default=False)),
            ],
            options={
                'db_table': '"gestion_documental"."estados_revision"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistorialEstadoVersion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('cambiado_en', models.DateTimeField()),
            ],
            options={
                'db_table': '"gestion_documental"."historial_estados_version"',
                'ordering': ['-cambiado_en'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SolicitudRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comentario_solicitud', models.TextField(blank=True, null=True)),
                ('comentario_resolucion', models.TextField(blank=True, null=True)),
                ('solicitada_en', models.DateTimeField()),
                ('resuelta_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': '"gestion_documental"."solicitudes_revision"',
                'ordering': ['-solicitada_en'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ComentarioRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('OBSERVACION', 'Observacion'), ('RESPUESTA', 'Respuesta'), ('RESOLUCION', 'Resolucion')], default='OBSERVACION', max_length=20)),
                ('contenido', models.TextField()),
                ('resuelto', models.BooleanField(default=False)),
                ('resuelto_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(db_column='autor_id', on_delete=django.db.models.deletion.PROTECT, related_name='comentarios_revision', to='documentos.usuariodocumental')),
                ('comentario_padre', models.ForeignKey(blank=True, db_column='comentario_padre_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='documentos.comentariorevision')),
                ('resuelto_por', models.ForeignKey(blank=True, db_column='resuelto_por_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comentarios_resueltos', to='documentos.usuariodocumental')),
                ('solicitud', models.ForeignKey(db_column='solicitud_revision_id', on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='documentos.solicitudrevision')),
            ],
            options={
                'db_table': '"gestion_documental"."revision_comentarios"',
                'ordering': ['creado_en'],
            },
        ),
        migrations.CreateModel(
            name='DetalleSolicitudRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_limite', models.DateTimeField(blank=True, null=True)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('solicitud', models.OneToOneField(db_column='solicitud_revision_id', on_delete=django.db.models.deletion.CASCADE, related_name='detalle', to='documentos.solicitudrevision')),
            ],
            options={
                'db_table': '"gestion_documental"."solicitudes_revision_detalle"',
            },
        ),
        migrations.CreateModel(
            name='ElementoChecklistRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('titulo', models.CharField(max_length=255)),
                ('completada', models.BooleanField(default=False)),
                ('completada_en', models.DateTimeField(blank=True, null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('completada_por', models.ForeignKey(blank=True, db_column='completada_por_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checklist_completada', to='documentos.usuariodocumental')),
                ('solicitud', models.ForeignKey(db_column='solicitud_revision_id', on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='documentos.solicitudrevision')),
            ],
            options={
                'db_table': '"gestion_documental"."revisiones_checklist"',
                'ordering': ['orden', 'creada_en'],
            },
        ),
    ]
