# Generated by Django 5.2.17 on 2026-08-27 00:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0006_estadorevisioncatalogo_historialestadoversion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoritoDocumento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(db_column='documento_id', on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='documentos.documento')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='documentos_favoritos', to='documentos.usuariodocumental')),
            ],
            options={
                'db_table': '"gestion_documental"."documentos_favoritos"',
                'indexes': [models.Index(fields=['usuario', '-creado_en'], name='ix_favoritos_usuario_fecha')],
                'constraints': [models.UniqueConstraint(fields=('documento', 'usuario'), name='uq_documentos_favoritos_documento_usuario')],
            },
        ),
        migrations.CreateModel(
            name='RegistroAccesoDocumento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('CONSULTA', 'Consulta'), ('LECTURA', 'Lectura'), ('DESCARGA', 'Descarga'), ('VISTA_PREVIA', 'Vista previa')], max_length=20)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('duracion_segundos', models.PositiveIntegerField(blank=True, null=True)),
                ('pagina_final', models.PositiveIntegerField(blank=True, null=True)),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('agente_usuario', models.TextField(blank=True, null=True)),
                ('registrado_en', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(db_column='documento_id', on_delete=django.db.models.deletion.CASCADE, related_name='registros_acceso', to='documentos.documento')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.PROTECT, related_name='accesos_documentales', to='documentos.usuariodocumental')),
                ('version_documento', models.ForeignKey(db_column='version_documento_id', on_delete=django.db.models.deletion.CASCADE, related_name='registros_acceso', to='documentos.archivodocumento')),
            ],
            options={
                'db_table': '"gestion_documental"."documentos_accesos"',
                'ordering': ['-registrado_en'],
                'indexes': [models.Index(fields=['usuario', '-registrado_en'], name='ix_accesos_usuario_fecha'), models.Index(fields=['documento', '-registrado_en'], name='ix_accesos_documento_fecha'), models.Index(fields=['tipo', '-registrado_en'], name='ix_accesos_tipo_fecha')],
            },
        ),
    ]
