# Generated by Django 5.2.17 on 2026-08-27 00:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0007_lector_accesos_favoritos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('REVISION_ASIGNADA', 'Revision asignada'), ('COMENTARIO_REVISION', 'Comentario de revision'), ('APROBACION_REVISION', 'Revision aprobada'), ('DEVOLUCION_REVISION', 'Revision devuelta'), ('RECHAZO_REVISION', 'Revision rechazada'), ('PUBLICACION_DOCUMENTO', 'Documento publicado')], max_length=30)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('leida_en', models.DateTimeField(blank=True, null=True)),
                ('correo_enviado_en', models.DateTimeField(blank=True, null=True)),
                ('error_correo', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(blank=True, db_column='documento_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='documentos.documento')),
                ('solicitud_revision', models.ForeignKey(blank=True, db_column='solicitud_revision_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='documentos.solicitudrevision')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='documentos.usuariodocumental')),
                ('version_documento', models.ForeignKey(blank=True, db_column='version_documento_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='documentos.archivodocumento')),
            ],
            options={
                'db_table': '"gestion_documental"."notificaciones"',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['usuario', 'leida_en', '-creado_en'], name='ix_notif_usuario_estado_fecha'), models.Index(fields=['tipo', '-creado_en'], name='ix_notif_tipo_fecha')],
            },
        ),
    ]
