# Generated by Django 5.2.17 on 2026-08-27 02:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0011_reportes_v2'),
    ]

    operations = [
        migrations.RunSQL(
            sql='''
                CREATE TABLE IF NOT EXISTS gestion_documental.configuraciones_respaldo_v2 (
                    id uuid PRIMARY KEY,
                    organizacion_id uuid NOT NULL UNIQUE,
                    activa boolean NOT NULL DEFAULT TRUE,
                    frecuencia varchar(20) NOT NULL DEFAULT 'daily',
                    retencion_dias integer NOT NULL DEFAULT 30,
                    destino varchar(20) NOT NULL DEFAULT 's3',
                    incluir_archivos boolean NOT NULL DEFAULT TRUE,
                    cifrar boolean NOT NULL DEFAULT TRUE,
                    proxima_ejecucion_en timestamptz,
                    ultima_ejecucion_en timestamptz,
                    ultima_prueba_en timestamptz,
                    actualizada_en timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
                );
                CREATE TABLE IF NOT EXISTS gestion_documental.respaldos_v2 (
                    id uuid PRIMARY KEY,
                    organizacion_id uuid NOT NULL,
                    creado_por_id uuid,
                    tipo varchar(20) NOT NULL,
                    destino varchar(20) NOT NULL,
                    nombre varchar(200) NOT NULL,
                    clave_almacenamiento text,
                    tamano_bytes bigint NOT NULL DEFAULT 0,
                    sha256 varchar(64) NOT NULL DEFAULT '',
                    archivos integer NOT NULL DEFAULT 0,
                    registros_db integer NOT NULL DEFAULT 0,
                    cifrado boolean NOT NULL DEFAULT TRUE,
                    estado varchar(20) NOT NULL,
                    error text,
                    iniciado_en timestamptz NOT NULL,
                    finalizado_en timestamptz,
                    retencion_hasta timestamptz,
                    restaurado_en timestamptz
                );
                CREATE INDEX IF NOT EXISTS ix_respaldos_v2_org_fecha
                    ON gestion_documental.respaldos_v2 (organizacion_id, iniciado_en DESC);
                CREATE INDEX IF NOT EXISTS ix_respaldos_v2_org_estado
                    ON gestion_documental.respaldos_v2 (organizacion_id, estado);
            ''',
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='ConfiguracionRespaldo',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('organizacion_id', models.UUIDField(unique=True)),
                        ('activa', models.BooleanField(default=True)),
                        ('frecuencia', models.CharField(default='daily', max_length=20)),
                        ('retencion_dias', models.PositiveIntegerField(default=30)),
                        ('destino', models.CharField(default='s3', max_length=20)),
                        ('incluir_archivos', models.BooleanField(default=True)),
                        ('cifrar', models.BooleanField(default=True)),
                        ('proxima_ejecucion_en', models.DateTimeField(blank=True, null=True)),
                        ('ultima_ejecucion_en', models.DateTimeField(blank=True, null=True)),
                        ('ultima_prueba_en', models.DateTimeField(blank=True, null=True)),
                        ('actualizada_en', models.DateTimeField()),
                    ],
                    options={'db_table': '"gestion_documental"."configuraciones_respaldo_v2"', 'managed': False},
                ),
                migrations.CreateModel(
                    name='Respaldo',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('organizacion_id', models.UUIDField()),
                        ('creado_por_id', models.UUIDField(blank=True, null=True)),
                        ('tipo', models.CharField(max_length=20)),
                        ('destino', models.CharField(max_length=20)),
                        ('nombre', models.CharField(max_length=200)),
                        ('clave_almacenamiento', models.TextField(blank=True, null=True)),
                        ('tamano_bytes', models.BigIntegerField(default=0)),
                        ('sha256', models.CharField(blank=True, max_length=64)),
                        ('archivos', models.PositiveIntegerField(default=0)),
                        ('registros_db', models.PositiveIntegerField(default=0)),
                        ('cifrado', models.BooleanField(default=True)),
                        ('estado', models.CharField(max_length=20)),
                        ('error', models.TextField(blank=True, null=True)),
                        ('iniciado_en', models.DateTimeField()),
                        ('finalizado_en', models.DateTimeField(blank=True, null=True)),
                        ('retencion_hasta', models.DateTimeField(blank=True, null=True)),
                        ('restaurado_en', models.DateTimeField(blank=True, null=True)),
                    ],
                    options={'db_table': '"gestion_documental"."respaldos_v2"', 'ordering': ['-iniciado_en'], 'managed': False},
                ),
            ],
        ),
    ]
