# Generated by Django 5.2.17 on 2026-08-27 03:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0012_configuracionrespaldo_respaldo'),
    ]

    operations = [
        migrations.RunSQL(
            sql='''
                CREATE TABLE IF NOT EXISTS gestion_documental.configuraciones_sistema_v2 (
                    id uuid PRIMARY KEY,
                    organizacion_id uuid NOT NULL UNIQUE,
                    general jsonb NOT NULL DEFAULT '{}'::jsonb,
                    seguridad jsonb NOT NULL DEFAULT '{}'::jsonb,
                    smtp jsonb NOT NULL DEFAULT '{}'::jsonb,
                    carga jsonb NOT NULL DEFAULT '{}'::jsonb,
                    apariencia jsonb NOT NULL DEFAULT '{}'::jsonb,
                    notificaciones jsonb NOT NULL DEFAULT '{}'::jsonb,
                    integraciones jsonb NOT NULL DEFAULT '{}'::jsonb,
                    actualizado_en timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
                );
            ''',
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[migrations.CreateModel(
                name='ConfiguracionSistema',
                fields=[
                    ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                    ('organizacion_id', models.UUIDField(unique=True)),
                    ('general', models.JSONField(default=dict)),
                    ('seguridad', models.JSONField(default=dict)),
                    ('smtp', models.JSONField(default=dict)),
                    ('carga', models.JSONField(default=dict)),
                    ('apariencia', models.JSONField(default=dict)),
                    ('notificaciones', models.JSONField(default=dict)),
                    ('integraciones', models.JSONField(default=dict)),
                    ('actualizado_en', models.DateTimeField()),
                ],
                options={'db_table': '"gestion_documental"."configuraciones_sistema_v2"', 'managed': False},
            )],
        ),
    ]
