from django.urls import path

from . import views
from . import management_views
from . import document_views
from . import workflow_views
from . import reader_views
from . import notification_views
from . import audit_views
from . import reports_views
from . import backup_views
from . import settings_views

urlpatterns = [
    path('auth/csrf/', views.CsrfTokenView.as_view(), name='auth-csrf'),
    path('auth/login/', views.LoginView.as_view(), name='auth-login'),
    path('auth/me/', views.CurrentUserView.as_view(), name='auth-current-user'),
    path('auth/logout/', views.LogoutView.as_view(), name='auth-logout'),
    path('auth/change-password/', views.ChangePasswordView.as_view(), name='auth-change-password'),
    path('admin/users/', management_views.UserListCreateView.as_view(), name='admin-users'),
    path('admin/dashboard/', management_views.AdminDashboardView.as_view(), name='admin-dashboard'),
    path('admin/users/<uuid:user_id>/', management_views.UserDetailView.as_view(), name='admin-user-detail'),
    path('admin/users/<uuid:user_id>/status/', management_views.UserStatusView.as_view(), name='admin-user-status'),
    path('admin/users/<uuid:user_id>/lock/', management_views.UserLockView.as_view(), name='admin-user-lock'),
    path('admin/users/<uuid:user_id>/reset-password/', management_views.UserResetPasswordView.as_view(), name='admin-user-reset-password'),
    path('admin/users/<uuid:user_id>/roles/', management_views.UserRolesView.as_view(), name='admin-user-roles'),
    path('admin/users/<uuid:user_id>/sessions/', management_views.UserSessionsView.as_view(), name='admin-user-sessions'),
    path('admin/users/<uuid:user_id>/devices/<str:device_id>/revoke/', management_views.UserDeviceRevokeView.as_view(), name='admin-user-device-revoke'),
    path('admin/sessions/<uuid:session_id>/revoke/', management_views.SessionRevokeView.as_view(), name='admin-session-revoke'),
    path('admin/roles/', management_views.RoleListCreateView.as_view(), name='admin-roles'),
    path('admin/roles/<uuid:role_id>/', management_views.RoleDetailView.as_view(), name='admin-role-detail'),
    path('admin/roles/<uuid:role_id>/permissions/', management_views.RolePermissionsView.as_view(), name='admin-role-permissions'),
    path('admin/permissions/', management_views.PermissionListView.as_view(), name='admin-permissions'),
    path('admin/permissions/<uuid:permission_id>/', management_views.PermissionDetailView.as_view(), name='admin-permission-detail'),
    path('documents/', document_views.DocumentListCreateView.as_view(), name='documents'),
    path('documents/catalogs/', document_views.DocumentCatalogView.as_view(), name='document-catalogs'),
    path('documents/export/', document_views.DocumentExportView.as_view(), name='document-export'),
    path('documents/<uuid:document_id>/', document_views.DocumentDetailView.as_view(), name='document-detail'),
    path('documents/<uuid:document_id>/permissions/', document_views.DocumentPermissionsView.as_view(), name='document-permissions'),
    path('documents/<uuid:document_id>/archive/', document_views.DocumentArchiveView.as_view(), name='document-archive'),
    path('documents/<uuid:document_id>/unarchive/', document_views.DocumentUnarchiveView.as_view(), name='document-unarchive'),
    path('documents/<uuid:document_id>/files/', document_views.DocumentFileListCreateView.as_view(), name='document-files'),
    path('documents/<uuid:document_id>/versions/', document_views.DocumentVersionListView.as_view(), name='document-versions'),
    path('documents/<uuid:document_id>/versions/<uuid:version_id>/restore/', document_views.DocumentVersionRestoreView.as_view(), name='document-version-restore'),
    path('documents/<uuid:document_id>/versions/compare/', document_views.DocumentVersionCompareView.as_view(), name='document-version-compare'),
    path('documents/<uuid:document_id>/timeline/', document_views.DocumentVersionTimelineView.as_view(), name='document-version-timeline'),
    path(
        'documents/<uuid:document_id>/versions/<uuid:version_id>/submit-review/',
        workflow_views.ReviewSubmitView.as_view(),
        name='review-submit',
    ),
    path('reviews/inbox/', workflow_views.ReviewInboxView.as_view(), name='review-inbox'),
    path('reviews/<uuid:review_id>/', workflow_views.ReviewDetailView.as_view(), name='review-detail'),
    path('reviews/<uuid:review_id>/assign/', workflow_views.ReviewAssignmentView.as_view(), name='review-assign'),
    path('reviews/<uuid:review_id>/approve/', workflow_views.ReviewApproveView.as_view(), name='review-approve'),
    path('reviews/<uuid:review_id>/return/', workflow_views.ReviewReturnView.as_view(), name='review-return'),
    path('reviews/<uuid:review_id>/reject/', workflow_views.ReviewRejectView.as_view(), name='review-reject'),
    path('reviews/<uuid:review_id>/comments/', workflow_views.ReviewCommentListCreateView.as_view(), name='review-comments'),
    path('reviews/<uuid:review_id>/checklist/', workflow_views.ReviewChecklistCreateView.as_view(), name='review-checklist'),
    path('reviews/checklist/<uuid:item_id>/', workflow_views.ReviewChecklistUpdateView.as_view(), name='review-checklist-item'),
    path('reviews/comments/<uuid:comment_id>/resolve/', workflow_views.ReviewCommentResolveView.as_view(), name='review-comment-resolve'),
    path(
        'documents/<uuid:document_id>/versions/<uuid:version_id>/publish/',
        workflow_views.VersionPublishView.as_view(),
        name='version-publish',
    ),
    path(
        'documents/<uuid:document_id>/files/<uuid:file_id>/download/',
        document_views.DocumentFileDownloadView.as_view(),
        name='document-file-download',
    ),
    path(
        'documents/<uuid:document_id>/versions/<uuid:version_id>/download/',
        document_views.DocumentVersionDownloadView.as_view(),
        name='document-version-download',
    ),
    path(
        'documents/<uuid:document_id>/files/<uuid:file_id>/preview/',
        document_views.DocumentFilePreviewView.as_view(),
        name='document-file-preview',
    ),
    path('reader/documents/', reader_views.ReaderDocumentListView.as_view(), name='reader-documents'),
    path('reader/documents/<uuid:document_id>/', reader_views.ReaderDocumentDetailView.as_view(), name='reader-document-detail'),
    path('reader/documents/<uuid:document_id>/read/', reader_views.ReaderDocumentReadView.as_view(), name='reader-document-read'),
    path('reader/documents/<uuid:document_id>/favorite/', reader_views.ReaderFavoriteView.as_view(), name='reader-favorite'),
    path('reader/history/', reader_views.ReaderReadingHistoryView.as_view(), name='reader-history'),
    path('reader/favorites/', reader_views.ReaderFavoritesView.as_view(), name='reader-favorites'),
    path('reader/documents/<uuid:document_id>/versions/<uuid:version_id>/download/', reader_views.ReaderVersionDownloadView.as_view(), name='reader-version-download'),
    path('reader/documents/<uuid:document_id>/versions/<uuid:version_id>/preview/', reader_views.ReaderVersionPreviewView.as_view(), name='reader-version-preview'),
    path('notifications/', notification_views.NotificationListView.as_view(), name='notifications'),
    path('notifications/read-all/', notification_views.NotificationReadAllView.as_view(), name='notifications-read-all'),
    path('notifications/<uuid:notification_id>/read/', notification_views.NotificationReadView.as_view(), name='notification-read'),
    path('audit/', audit_views.AuditListView.as_view(), name='audit-list'),
    path('audit/export/', audit_views.AuditExportView.as_view(), name='audit-export'),
    path('audit/alerts/', audit_views.AuditAlertsView.as_view(), name='audit-alerts'),
    path('reports/', reports_views.ReportListView.as_view(), name='reports'),
    path('reports/generate/', reports_views.ReportGenerateView.as_view(), name='reports-generate'),
    path('reports/<uuid:report_id>/download/', reports_views.ReportDownloadView.as_view(), name='reports-download'),
    path('reports/schedules/', reports_views.ReportScheduleListView.as_view(), name='reports-schedules'),
    path('reports/schedules/<uuid:schedule_id>/', reports_views.ReportScheduleDetailView.as_view(), name='reports-schedule-detail'),
    path('backups/', backup_views.BackupListView.as_view(), name='backups'),
    path('backups/config/', backup_views.BackupConfigurationView.as_view(), name='backups-config'),
    path('backups/<uuid:backup_id>/download/', backup_views.BackupDownloadView.as_view(), name='backup-download'),
    path('backups/<uuid:backup_id>/restore/', backup_views.BackupRestoreView.as_view(), name='backup-restore'),
    path('backups/recovery-test/', backup_views.RecoveryTestView.as_view(), name='backup-recovery-test'),
    path('settings/', settings_views.SystemSettingsView.as_view(), name='system-settings'),
    path('settings/smtp/test/', settings_views.SmtpTestView.as_view(), name='settings-smtp-test'),
    path('settings/integrations/<str:provider>/test/', settings_views.IntegrationTestView.as_view(), name='settings-integration-test'),
    path('health/', views.HealthView.as_view(), name='health'),
]
